#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'client', 'config.js');
const apiBase = process.env.API_BASE_URL || '';

let content = '// Auto-generated by scripts/generate-config.js\n';
content += '// Do not edit by hand — set API_BASE_URL at build time.\n';
content += 'window.__API_BASE_URL__ = ' + (apiBase ? JSON.stringify(apiBase.replace(/\/$/, '')) : "''") + ';\n';

fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('Wrote ' + outPath + ' (API_BASE_URL=' + (apiBase || '(empty)') + ')');
